version: 2
updates:
  # Python dependencies via Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "TheHenrick"
    commit-message:
      prefix: "dependencies"
      include: "scope"
    # Apply security updates immediately
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "TheHenrick"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "TheHenrick"
    commit-message:
      prefix: "docker"
      include: "scope"
